export default {
  login: 'SerwinKastaneer05',
  id: 98677021,
  node_id: 'U_kgDOBeGxHQ',
  avatar_url: 'https://avatars.githubusercontent.com/u/98677021?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/SerwinKastaneer05',
  html_url: 'https://github.com/SerwinKastaneer05',
  followers_url: 'https://api.github.com/users/SerwinKastaneer05/followers',
  following_url:
    'https://api.github.com/users/SerwinKastaneer05/following{/other_user}',
  gists_url: 'https://api.github.com/users/SerwinKastaneer05/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/SerwinKastaneer05/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/SerwinKastaneer05/subscriptions',
  organizations_url: 'https://api.github.com/users/SerwinKastaneer05/orgs',
  repos_url: 'https://api.github.com/users/SerwinKastaneer05/repos',
  events_url: 'https://api.github.com/users/SerwinKastaneer05/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/SerwinKastaneer05/received_events',
  type: 'User',
  site_admin: false,
  name: 'Serwin Kastaneer',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 10,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2022-01-30T03:18:07Z',
  updated_at: '2022-10-20T14:58:46Z',
}
